name: Publish MauiSystemFontFamily to NuGet

on:
  push:
    branches:
      - main

jobs:
  build-and-pack:
    runs-on: ubuntu-latest
    outputs:
      package_name: ${{ steps.get_package_name.outputs.PACKAGE_NAME }}
      package_version: ${{ steps.get_package_version.outputs.PACKAGE_VERSION }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore MauiSystemFontFamily/MauiSystemFontFamily.csproj

    - name: Build
      run: dotnet build MauiSystemFontFamily/MauiSystemFontFamily.csproj --configuration Release --no-restore

    - name: Pack
      run: dotnet pack MauiSystemFontFamily/MauiSystemFontFamily.csproj --configuration Release --no-build --output ./nuget-packages

    - name: Check for nupkgs directory (Main)
      if: always()
      run: |
        echo "Checking ./nuget-packages for Main:"
        Test-Path ./nuget-packages
        Get-ChildItem ./nuget-packages -Filter *.nupkg
      shell: pwsh

    - name: Publish Main Library to NuGet
      run: |
        Get-ChildItem -Path ./nuget-packages -Filter *.nupkg | ForEach-Object { 
          Write-Host "Pushing package: $($_.FullName)"
          dotnet nuget push $_.FullName --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        }
      shell: pwsh
